### PR TITLE
Unblock build by updating AGP and libraries

### LINKED ISSUE #45: Fix JDK and Kotlin Version Build Compatibility (Java 21 vs Kotlin 1.6.21)
The current build fails due to an incompatibility between Java 21 and Kotlin 1.6.21. This is an environment configuration issue, not related to the project code itself.

---

#### Root `build.gradle`
[View file on GitHub](https://github.com/VictorHerreraO/bdates/blob/3390f461e5f5a58da65312a9095e53d337fceb26/build.gradle)
```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.21"
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.46.1'
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.6.0"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

#### `app/build.gradle`
[View file on GitHub](https://github.com/VictorHerreraO/bdates/blob/3390f461e5f5a58da65312a9095e53d337fceb26/app/build.gradle)
```gradle
android {
    ...
    compileSdk 34
    defaultConfig {
        ...
        minSdk 26
        targetSdk 34
        ...
    }
    buildTypes {
        ...
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    ...
}
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.21"
    ...
}
```
---

**Error snippet:**
```
Build currently fails due to Java 21 vs Kotlin 1.6.21 compatibility issue. This is an environment configuration issue, not a code issue
```

---
**Steps to address:**
- Investigate and document the compatibility problem between Java 21 and Kotlin 1.6.21.
- Propose and implement an environment configuration adjustment so the project builds successfully.
- Consider downgrading JDK or upgrading Kotlin as appropriate.
- Update documentation/build scripts as needed.

---

**Attribution:**
This issue was partially generated with the assistance of GitHub Copilot. Significant build analysis and snippet gathering was performed by the agent.

### PR DESCRIPTION
**Pull request by VictorHerreraO**
Closes #45

## Description

This PR addresses build failures related to Java 21 and Kotlin 1.6.21 by updating the project's build configuration and dependencies.

The Java 21 issues were caused by an incorrect configuration on JAVA_HOME but there were some incompatibilities with the AGP version and the libraries we were using.

- **Summary of changes**
  - Upgraded AGP to 9.0.1
  - Upgraded Kotlin to 2.2.10
  - Upgraded Hilt to 2.59.1
  - Upgraded Navigation to 2.9.7
  - Upgraded Room to 2.8.4
  - Set JVM target to 17
  - Removed KAPT

## Docs

Updated build configurations.

## Ready?

- [x] Ran the linter to ensure style guidelines were followed

### CODE REVIEW

File: app/src/test/java/com/soyvictorherrera/bdates/modules/eventList/framework/presentation/EventListViewModelTest.kt [hunk 1]
```diff
@@ -70,8 +68,31 @@ class EventListViewModelTest {
         coEvery { getDayEventList.execute() } returns (emptyList())
         coEvery { filterEventListUseCase.execute(any()) } returns Result.success(events)
 
+        // Re-init to trigger data load with mocked responses if needed,
```
Comment (VictorHerreraO) [inline app/src/test/java/com/soyvictorherrera/bdates/modules/eventList/framework/presentation/EventListViewModelTest.kt:71]: Remove this
